# Generated by Django 5.1.5 on 2025-01-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.JSONField(default=dict, verbose_name="Список блюд с ценами"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("ready", "Готово"),
                    ("paid", "Оплачено"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Общая стоимость",
            ),
        ),
    ]
