# Generated by Django 5.1.5 on 2025-01-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_items_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.JSONField(default=dict, verbose_name="Список блюд"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("ready", "Готово"),
                    ("paid", "Оплачено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="table_number",
            field=models.PositiveIntegerField(verbose_name="Номер стола"),
        ),
    ]
